### ISSUE TITLE
Zoom Blackout starting around 150% (168%)

### ISSUE THREAD

**Issue by pitkz** [Robin-Sch/Xournalpp-Infinity-Notes#2]
Hey Robin,

despite being a bit laggy already with "local infinity = 15000" I noticed that my maximum zoom is 164%: As soon as I hit 168% the entire page becomes blank?

164%
![Screenshot from 2024-11-29 21-35-09](https://github.com/user-attachments/assets/e8b04d0b-aee8-4caf-bbe8-926baef468be)

168%
![Screenshot from 2024-11-29 21-35-04](https://github.com/user-attachments/assets/1556b0e4-fd26-48b7-b26f-4257b605bb68)

Are you aware of that?

Cheers

**Comment by Robin-Sch** [comment]
For me this happens after 200+%, it maybe depends on the scale/resolution of the monitor?
Lowering the 15000 should allow you to zoom more

**Comment by Robin-Sch** [comment]
I have pushed a new commit that decreased the infinity level and now it should be better?
Also, if you use the nightly build it will automatically zoom in!

**Comment by Robin-Sch** [comment]
Feel free to re-open this issue if you still experience this blackout
